Cds 765 - release notes update
CBIIT/bento-cds-frontend pull request #161
Opened 2024-03-01 17:10 UTC by huuaho

release notes now pull from the url described in the environment variable

[CDS-765](https://tracker.nci.nih.gov/browse/CDS-765)

2024-03-04 21:37 UTC, iksheth approved these changes

2024-03-04 21:38 UTC, iksheth requested changes
@huuaho Can you add "REACT_APP_DATA_RELEASES_URL" in injectEnv.js file?

2024-03-05 17:50 UTC, huuaho commented
I've added the environment variable pointing to the dev endpoint for the release notes.

2024-03-06 13:06 UTC, iksheth approved these changes

2024-03-06 13:06 UTC, merged